server:
  port: 8888



spring:
  datasource:
    url: jdbc:mysql://localhost:3306/word?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true      #设置驼峰命名规则自动转换

# 配置文件加密key
jasypt:
  encryptor:
    password: panther